python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_1.pkl autonomooseFirst/test_conf_rep_1.pkl ../FullTraces/autonomooseFirst/ > autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_2.pkl autonomooseFirst/test_conf_rep_2.pkl ../FullTraces/autonomooseFirst/ | tail -n1 >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_3.pkl autonomooseFirst/test_conf_rep_3.pkl ../FullTraces/autonomooseFirst/ | tail -n1  >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_4.pkl autonomooseFirst/test_conf_rep_4.pkl ../FullTraces/autonomooseFirst/ | tail -n1 >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_5.pkl autonomooseFirst/test_conf_rep_5.pkl ../FullTraces/autonomooseFirst/ | tail -n1  >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_6.pkl autonomooseFirst/test_conf_rep_6.pkl ../FullTraces/autonomooseFirst/ | tail -n1  >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_7.pkl autonomooseFirst/test_conf_rep_7.pkl ../FullTraces/autonomooseFirst/ | tail -n1  >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_8.pkl autonomooseFirst/test_conf_rep_8.pkl ../FullTraces/autonomooseFirst/ | tail -n1  >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_9.pkl autonomooseFirst/test_conf_rep_9.pkl ../FullTraces/autonomooseFirst/ | tail -n1  >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseFirst/train_conf_rep_10.pkl autonomooseFirst/test_conf_rep_10.pkl ../FullTraces/autonomooseFirst/ | tail -n1  >> autonomooseFirst/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_1.pkl autonomooseSecond/test_conf_rep_1.pkl ../FullTraces/autonomooseSecond/ > autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_2.pkl autonomooseSecond/test_conf_rep_2.pkl ../FullTraces/autonomooseSecond/ | tail -n1 >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_3.pkl autonomooseSecond/test_conf_rep_3.pkl ../FullTraces/autonomooseSecond/ | tail -n1  >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_4.pkl autonomooseSecond/test_conf_rep_4.pkl ../FullTraces/autonomooseSecond/ | tail -n1 >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_5.pkl autonomooseSecond/test_conf_rep_5.pkl ../FullTraces/autonomooseSecond/ | tail -n1  >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_6.pkl autonomooseSecond/test_conf_rep_6.pkl ../FullTraces/autonomooseSecond/ | tail -n1  >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_7.pkl autonomooseSecond/test_conf_rep_7.pkl ../FullTraces/autonomooseSecond/ | tail -n1  >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_8.pkl autonomooseSecond/test_conf_rep_8.pkl ../FullTraces/autonomooseSecond/ | tail -n1  >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_9.pkl autonomooseSecond/test_conf_rep_9.pkl ../FullTraces/autonomooseSecond/ | tail -n1  >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseSecond/train_conf_rep_10.pkl autonomooseSecond/test_conf_rep_10.pkl ../FullTraces/autonomooseSecond/ | tail -n1  >> autonomooseSecond/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_1.pkl autonomooseThird/test_conf_rep_1.pkl ../FullTraces/autonomooseThird/ > autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_2.pkl autonomooseThird/test_conf_rep_2.pkl ../FullTraces/autonomooseThird/ | tail -n1 >> autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_3.pkl autonomooseThird/test_conf_rep_3.pkl ../FullTraces/autonomooseThird/ | tail -n1  >> autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_4.pkl autonomooseThird/test_conf_rep_4.pkl ../FullTraces/autonomooseThird/ | tail -n1 >> autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_5.pkl autonomooseThird/test_conf_rep_5.pkl ../FullTraces/autonomooseThird/ | tail -n1  >> autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_6.pkl autonomooseThird/test_conf_rep_6.pkl ../FullTraces/autonomooseThird/ | tail -n1  >> autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_7.pkl autonomooseThird/test_conf_rep_7.pkl ../FullTraces/autonomooseThird/ | tail -n1  >> autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_8.pkl autonomooseThird/test_conf_rep_8.pkl ../FullTraces/autonomooseThird/ | tail -n1  >> autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_9.pkl autonomooseThird/test_conf_rep_9.pkl ../FullTraces/autonomooseThird/ | tail -n1  >> autonomooseThird/results/rq2_fse_control.csv
python -m FSELearning.AnalyzeRQ2WithFSE  autonomoose autonomooseThird/train_conf_rep_10.pkl autonomooseThird/test_conf_rep_10.pkl ../FullTraces/autonomooseThird/ | tail -n1  >> autonomooseThird/results/rq2_fse_control.csv
