python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_1.pkl > $4rq2_predictions_rep_1.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_2.pkl > $4rq2_predictions_rep_2.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_3.pkl > $4rq2_predictions_rep_3.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_4.pkl > $4rq2_predictions_rep_4.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_5.pkl > $4rq2_predictions_rep_5.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_6.pkl > $4rq2_predictions_rep_6.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_7.pkl > $4rq2_predictions_rep_7.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_8.pkl > $4rq2_predictions_rep_8.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_9.pkl > $4rq2_predictions_rep_9.csv
python -u AnalyzerRQ2.py $1 $2 $3regressors_rep_1.pkl $3test_conf_rep_10.pkl > $4rq2_predictions_rep_10.csv
