python GenerateAndSaveRegressors.py $1 $2sampled_rep_1.pkl  $2train_conf_rep_1.pkl $3best_method_rep_1.csv $2regressors_rep_1.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_2.pkl  $2train_conf_rep_2.pkl $3best_method_rep_2.csv $2regressors_rep_2.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_3.pkl  $2train_conf_rep_3.pkl $3best_method_rep_3.csv $2regressors_rep_3.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_4.pkl  $2train_conf_rep_4.pkl $3best_method_rep_4.csv $2regressors_rep_4.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_5.pkl  $2train_conf_rep_5.pkl $3best_method_rep_5.csv $2regressors_rep_5.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_6.pkl  $2train_conf_rep_6.pkl $3best_method_rep_6.csv $2regressors_rep_6.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_7.pkl  $2train_conf_rep_7.pkl $3best_method_rep_7.csv $2regressors_rep_7.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_8.pkl  $2train_conf_rep_8.pkl $3best_method_rep_8.csv $2regressors_rep_8.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_9.pkl  $2train_conf_rep_9.pkl $3best_method_rep_9.csv $2regressors_rep_9.pkl
python GenerateAndSaveRegressors.py $1 $2sampled_rep_10.pkl  $2train_conf_rep_10.pkl $3best_method_rep_10.csv $2regressors_rep_10.pkl
