python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_1.pkl $4sampled_rep_1.pkl  
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_2.pkl $4sampled_rep_2.pkl  
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_3.pkl $4sampled_rep_3.pkl  
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_1.pkl $4sampled_rep_1.pkl
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_2.pkl $4sampled_rep_2.pkl
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_3.pkl $4sampled_rep_3.pkl
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_4.pkl $4sampled_rep_4.pkl
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_5.pkl $4sampled_rep_5.pkl
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_6.pkl $4sampled_rep_6.pkl  
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_7.pkl $4sampled_rep_7.pkl 
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_8.pkl $4sampled_rep_8.pkl 
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_9.pkl $4sampled_rep_9.pkl  
python IntegratedSampledDataCreation.py $1 $2 $3 $4train_conf_rep_10.pkl $4sampled_rep_10.pkl
