python GenerateAndSaveRegressors.py $1 sampled_rep_2.pkl  train_conf_rep_2.pkl best_method_rep_2.csv regressors_rep_2.pkl
python GenerateAndSaveRegressors.py $1 sampled_rep_3.pkl  train_conf_rep_3.pkl best_method_rep_3.csv regressors_rep_3.pkl
python GenerateAndSaveRegressors.py $1 sampled_rep_4.pkl  train_conf_rep_4.pkl best_method_rep_4.csv regressors_rep_4.pkl
python GenerateAndSaveRegressors.py $1 sampled_rep_5.pkl  train_conf_rep_5.pkl best_method_rep_5.csv regressors_rep_5.pkl
python GenerateAndSaveRegressors.py $1 sampled_rep_6.pkl  train_conf_rep_6.pkl best_method_rep_6.csv regressors_rep_6.pkl
python GenerateAndSaveRegressors.py $1 sampled_rep_7.pkl  train_conf_rep_7.pkl best_method_rep_7.csv regressors_rep_7.pkl
python GenerateAndSaveRegressors.py $1 sampled_rep_8.pkl  train_conf_rep_8.pkl best_method_rep_8.csv regressors_rep_8.pkl
python GenerateAndSaveRegressors.py $1 sampled_rep_9.pkl  train_conf_rep_9.pkl best_method_rep_9.csv regressors_rep_9.pkl
python GenerateAndSaveRegressors.py $1 sampled_rep_10.pkl  train_conf_rep_10.pkl best_method_rep_10.csv regressors_rep_10.pkl
